---
- include_tasks: redhat8.yml
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")
    - ansible_distribution_major_version == "8"

- include_tasks: ubuntu.yml
  when:
    - (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")
