---

- name: HIGH | RHEL-09-611025 | PATCH |  RHEL 9 must not allow blank or null passwords.
  when: rhel_09_611025
  tags:
    - RHEL-09-611025
    - CAT1
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-258094r1045187_rule
    - V-258094
    - NIST800-53R4_CM-6
    - pam
  ansible.builtin.replace:
    path: "{{ null_pass }}"
    regexp: (.*) nullok(.*)
    replace: \1\2
  loop:
    - /etc/pam.d/system-auth
    - /etc/pam.d/password-auth
  loop_control:
    loop_var: null_pass

- name: HIGH | RHEL-09-671010 | PATCH | RHEL 9 must enable FIPS mode.
  when:
    - rhel_09_671010
    - not ansible_fips
  tags:
    - RHEL-09-671010
    - CAT1
    - CCI-00068
    - CCI-00877
    - CCI-002418
    - CCI-002450
    - SRG-OS-000033-GPOS-00014
    - SRG-OS-000125-GPOS-00065
    - SRG-OS-000396-GPOS-00176
    - SRG-OS-000423-GPOS-00187
    - SRG-OS-000478-GPOS-00223
    - SV-258230r958408_rule
    - V-258230
    - NIST800-53R4_AC-17
    - NIST800-53R4_MA-4
    - NIST800-53R4_SC-8
    - NIST800-53R4_SC-13
    - fips
  vars:
    warn_control_id: "HIGH | RHEL-09-671010"
  notify: Change_requires_reboot
  block:
    - name: HIGH | RHEL-09-671010 | AUDIT | RHEL 9 must enable FIPS mode | Check current state.
      ansible.builtin.command: fips-mode-setup --check
      changed_when: false
      failed_when: discovered_current_fips_mode.rc not in [ 0 , 1 ]
      register: discovered_current_fips_mode

    - name: HIGH | RHEL-09-671010 | PATCH | RHEL 9 must enable FIPS mode.
      when:
        - rhel9stig_disruption_high
        - "'disabled' in discovered_current_fips_mode.stdout or 'Inconsistent' in discovered_current_fips_mode.stdout"
      ansible.builtin.command: fips-mode-setup --enable
      changed_when: true

    - name: HIGH | RHEL-09-671010 | WARN | RHEL 9 must enable FIPS mode. | Give Warning
      when:
        - not rhel9stig_disruption_high
        - "'disabled' in discovered_current_fips_mode.stdout or 'Inconsistent' in discovered_current_fips_mode.stdout"
      ansible.builtin.debug:
        msg: WARNING!! - FIPS mode not setup

    - name: HIGH | RHEL-09-671010 | WARN | RHEL 9 must enable FIPS mode. | Warning Count
      when:
        - not rhel9stig_disruption_high
        - "'disabled' in discovered_current_fips_mode.stdout or 'Inconsistent' in discovered_current_fips_mode.stdout"
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "HIGH | RHEL-09-672020 | PATCH | RHEL 9 crypto policy must not be overridden."
  when: rhel_09_672020
  tags:
    - RHEL-09-672020
    - CAT1
    - CCI-002450
    - CCI-002890
    - CCI-003123
    - SRG-OS-000396-GPOS-00176
    - SRG-OS-000393-GPOS-00173
    - SRG-OS-000394-GPOS-00174
    - SV-258236r987791_rule
    - V-258236
    - NIST800-53R4_SC-13
    - NIST800-53R4_MA-4
    - crypto
  vars:
    warn_control_id: "HIGH | RHEL-09-672020"
  block:
    - name: "HIGH | RHEL-09-672020 | AUDIT | RHEL 9 crypto policy must not be overridden."
      ansible.builtin.shell: update-crypto-policies --check && echo PASS
      changed_when: false
      failed_when: discovered_crypto_policies_fips.rc not in [ 0, 1 ]
      register: discovered_crypto_policies_fips

    - name: "HIGH | RHEL-09-672020 | WARN | RHEL 9 crypto policy must not be overridden. | Re-Install Crypto-policies package"
      when:
        - discovered_crypto_policies_fips is defined
        - "'PASS' not in discovered_crypto_policies_fips.stdout"
        - rhel9stig_disruption_high
      ansible.builtin.command: dnf -y reinstall crypto-policies
      changed_when: true

    - name: "HIGH | RHEL-09-672020 | WARN | RHEL 9 crypto policy must not be overridden. | ReEnable FIPS"
      when:
        - discovered_crypto_policies_fips is defined
        - "'PASS' in discovered_crypto_policies_fips.stdout"
        - rhel9stig_disruption_high
      ansible.builtin.command: update-crypto-policies --set FIPS
      changed_when: true

    - name: "HIGH | RHEL-09-672020 | WARN | RHEL 9 crypto policy must not be overridden."
      when:
        - discovered_crypto_policies_fips is defined
        - discovered_crypto_policies_fips.stdout | length > 0
        - not rhel9stig_disruption_high
      ansible.builtin.debug:
        msg: "Warning!! Please Investigate 672020 - Crypto files not pointing to FIPS"

    - name: "HIGH | RHEL-09-672020 | WARN | RHEL 9 crypto policy must not be overridden."
      when:
        - discovered_crypto_policies_fips is defined
        - discovered_crypto_policies_fips.stdout | length > 0
        - not rhel9stig_disruption_high
      ansible.builtin.import_tasks:
        file: warning_facts.yml
