---

- name: "MEDIUM | RHEL-09-672025 | PATCH | RHEL 9 must use mechanisms meeting the requirements of applicable federal laws, executive orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module."
  when: rhel_09_672025
  tags:
    - RHEL-09-672025
    - CAT2
    - CCI-000803
    - SRG-OS-000120-GPOS-00061
    - SV-258237r1051256_rule
    - V-258237
    - NIST800-53R4_IA-7
    - crypto
  vars:
    warn_control_id: "MEDIUM | RHEL-09-672025"
  block:
    - name: "MEDIUM | RHEL-09-672025 | AUDIT | RHEL 9 must use mechanisms meeting the requirements of applicable federal laws, executive orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module. | current state"
      ansible.builtin.stat:
        path: /etc/crypto-policies/back-ends/krb5.config
      register: discovered_crypto_krb5_fips

    - name: "MEDIUM | RHEL-09-672025 | AUDIT | RHEL 9 must use mechanisms meeting the requirements of applicable federal laws, executive orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module. | Remove current config"
      when:
        - rhel9stig_disruption_high
        - discovered_crypto_krb5_fips.stat.exists
        - "'/usr/share/crypto-policies/DEFAULT/krb5.txt' not in discovered_crypto_krb5_fips.stat.lnk_source"
      ansible.builtin.file:
        path: /etc/crypto-policies/back-ends/krb5.config
        state: absent
      register: discovered_krb5_config_removed

    - name: "MEDIUM | RHEL-09-672025 | PATCH | RHEL 9 must use mechanisms meeting the requirements of applicable federal laws, executive orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module. | Create link"
      when:
        - rhel9stig_disruption_high
        - not discovered_crypto_krb5_fips.stat.exists or discovered_krb5_config_removed.changed  # noqa no-handler
      ansible.builtin.file:
        src: /usr/share/crypto-policies/DEFAULT/krb5.txt
        dest: /etc/crypto-policies/back-ends/krb5.config
        state: link

    - name: "MEDIUM | RHEL-09-672025 | WARN | RHEL 9 must use mechanisms meeting the requirements of applicable federal laws, executive orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module."
      when:
        - not rhel9stig_disruption_high
        - discovered_crypto_krb5_fips is defined
        - "'/usr/share/crypto-policies/DEFAULT/krb5.txt' not in discovered_crypto_krb5_fips.stat.lnk_source"
      ansible.builtin.debug:
        msg: "Warning!! Please Investigate 672025 - kerberos is not FIPS compliant"

    - name: "MEDIUM | RHEL-09-672025 | WARN | RHEL 9 must use mechanisms meeting the requirements of applicable federal laws, executive orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module."
      when:
        - not rhel9stig_disruption_high
        - discovered_crypto_krb5_fips is defined
        - "'/usr/share/crypto-policies/DEFAULT/krb5.txt' not in discovered_crypto_krb5_fips.stat.lnk_source"
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "MEDIUM | RHEL-09-672050 | PATCH | RHEL 9 must implement DOD-approved encryption in the bind package."
  when:
    - rhel_09_672050
    - "'bind' in ansible_facts.packages"
  tags:
    - RHEL-09-672050
    - CAT2
    - CCI-002418
    - CCI-002422
    - SRG-OS-000423-GPOS-00187
    - SRG-OS-000426-GPOS-00190
    - SV-258242r958908_rule
    - V-258242
    - NIST800-53R4_SC-8
    - bind
    - encryption
  ansible.builtin.lineinfile:
    path: /etc/named.conf
    regexp: ^(#|)\s*include "/etc/crypto-policies/back-ends/bind.config"
    line: 'include "/etc/crypto-policies/back-ends/bind.config";'
